In [5]:
arr = [1,2,3]
print(arr*5)
arr = [x*5 for x in arr]

print(arr)

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]
[5, 10, 15]


In [6]:
import numpy as np

arr = np.array([1,2,3])
arr = arr *5
print(arr)

[ 5 10 15]


Ndarray

In [14]:
import numpy as np 

#1d array 
arr1 = np.array([1,2,3])
 
#2d array -->> in a arry of arrya. like row colum 
arr2 = np.array([
    [1,2,3,4],
    [5,6,7,8]
])
 
#3d array 
arr3 = np.array([
    [
        [1,2,3,4],
        [5,6,7,8]
    ],
    [
        [1,2,3,4],
        [5,6,7,8]
    ]
])

 

#shape
print("see dimantion")
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

#shape
print("\nsee shape")
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)

#data type
print("\nsee data type")
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)


#data size
print("\nsee size")
print(arr1.size)
print(arr2.size)
print(arr3.size)


see dimantion
1
2
3

see shape
(3,)
(2, 4)
(2, 2, 4)

see data type
int64
int64
int64

see size
3
8
16


upcasting in numpy

In [ ]:

arr = np.array([1,2,3,4])
print(arr.dtype)

# upcasted to float 
arr = np.array([1,2,3,4.2])
print(arr.dtype)

# upcasted to string (unicode string)
arr = np.array([1,2,3,4.2,"5"])
print(arr.dtype)




int64
float64
<U32


Selecting a data type for an array 

In [30]:
import numpy as np 


arr1 = np.array([1,2,30], dtype=np.int8)

print(arr1.dtype)

arr1 =arr.astype(np.int64)
print(arr1.dtype)

st = {1,2,3}
print(st)
print(type(st))
st = np.array(list(st))
print(st.dtype)
print(st.ndim)

int8
int64
{1, 2, 3}
<class 'set'>
int64
1


Dictionary

In [40]:
dc = {"a":10, "b":20, "c":30}

# print(dc.keys())
# print(dc.values())
# print(dc.items())


# print(type(dc))
st = np.array(list(dc))
print(st)
print(st.dtype)
print(st.ndim)


['a' 'b' 'c']
<U1
1


Array createion with rendom values

In [43]:
arr = np.random.rand(2,3)

print(arr)

print("see dimantion")
print(arr.ndim) 

#shape
print("\nsee shape")
print(arr.shape)

#data type
print("\nsee data type")
print(arr.dtype)


#data size
print("\nsee size")
print(arr.size)

[[0.15697273 0.92720126 0.03708837]
 [0.77996129 0.50109238 0.57679015]]
see dimantion
2

see shape
(2, 3)

see data type
float64

see size
6


In [ ]:
import numpy as np 
# random int value np.random.randint(start,end,(shape))
arr = np.random.randint(1,10,(10,3))

print(arr)

print("see dimantion")
print(arr.ndim) 

#shape
print("\nsee shape")
print(arr.shape)

#data type
print("\nsee data type")
print(arr.dtype)


#data size
print("\nsee size")
print(arr.size)

[[9 9 2]
 [7 1 6]
 [5 4 2]
 [8 5 1]
 [2 3 4]
 [1 2 3]
 [3 4 7]
 [3 2 4]
 [6 9 7]
 [9 3 7]]
see dimantion
2

see shape
(10, 3)

see data type
int32

see size
30


In [49]:
import numpy as np 
# random int value np.random.uniform(start,end,(shape))
arr = np.random.uniform(1,10,(10,3))

print(arr)

print("see dimantion")
print(arr.ndim) 

#shape
print("\nsee shape")
print(arr.shape)

#data type
print("\nsee data type")
print(arr.dtype)


#data size
print("\nsee size")
print(arr.size)

[[1.37299808 3.17235359 6.77639763]
 [7.06199988 8.17241443 2.26274127]
 [5.88605561 6.71144873 1.00354615]
 [7.58993736 4.90141914 1.14887098]
 [4.93123321 2.55035381 8.89587168]
 [6.38867613 3.04569161 5.75706026]
 [2.35097725 7.84284207 3.81933714]
 [3.9464438  2.09830828 7.89093504]
 [7.70658452 5.45195654 8.21904943]
 [7.37146309 4.44530441 9.91401742]]
see dimantion
2

see shape
(10, 3)

see data type
float64

see size
30


In [57]:
import numpy as np 
# range -->>  np.range.uniform(first,end,range)
arr = np.arange(1,10,1)
print(arr)

#create metrix
arr = arr.reshape(3,3)
print(arr)

print("see dimantion")
print(arr.ndim) 

#shape
print("\nsee shape")
print(arr.shape)

#data type
print("\nsee data type")
print(arr.dtype)


#data size
print("\nsee size")
print(arr.size)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
see dimantion
2

see shape
(3, 3)

see data type
int64

see size
9


In [59]:
import numpy as np 
# linspace -->>  np.linespace(start,end, howmuch)
arr = np.linspace(1,10, 11)
print(arr)

 
 

print("see dimantion")
print(arr.ndim) 

#shape
print("\nsee shape")
print(arr.shape)

#data type
print("\nsee data type")
print(arr.dtype)


#data size
print("\nsee size")
print(arr.size)

[ 1.   1.9  2.8  3.7  4.6  5.5  6.4  7.3  8.2  9.1 10. ]
see dimantion
1

see shape
(11,)

see data type
float64

see size
11


In [63]:
import numpy as np 
# logspace -->>  np.logspace(start,end(included), howmuch)
arr = np.logspace(0,4, 5)
print(arr)

 
 

print("see dimantion")
print(arr.ndim) 

#shape
print("\nsee shape")
print(arr.shape)

#data type
print("\nsee data type")
print(arr.dtype)


#data size
print("\nsee size")
print(arr.size)

[1.e+00 1.e+01 1.e+02 1.e+03 1.e+04]
see dimantion
1

see shape
(5,)

see data type
float64

see size
5
