In [14]:
import numpy as np


arr = np.random.randint(1,100,size=(10,5)) #sample - 10 , feature - 5
print(arr)

print(f"\narr shap = {arr.shape}\n")

# At  covart row to column and column to row

b = arr.reshape(5,10)


print(b)
print(f"\nb shap = {b.shape}")
print(f"b dimantion = {b.ndim}")

#convart to 1 dimantion
flatten =b.flatten()
print(flatten)


# column_wise_flattening = np.ravel(b, order = "C")
column_wise_flattening = np.ravel(b, order = "F")

print(column_wise_flattening)

[[52 33 69 23 79]
 [14 57 43 54  3]
 [77 39 89 88 58]
 [46 25 46 43 75]
 [77 24 60 97 50]
 [11  4 77 57 60]
 [35 18 30 89 31]
 [54 93 54 32 38]
 [61 84 66 27 52]
 [42 79 86 77 50]]

arr shap = (10, 5)

[[52 33 69 23 79 14 57 43 54  3]
 [77 39 89 88 58 46 25 46 43 75]
 [77 24 60 97 50 11  4 77 57 60]
 [35 18 30 89 31 54 93 54 32 38]
 [61 84 66 27 52 42 79 86 77 50]]

b shap = (5, 10)
b dimantion = 2
[52 33 69 23 79 14 57 43 54  3 77 39 89 88 58 46 25 46 43 75 77 24 60 97
 50 11  4 77 57 60 35 18 30 89 31 54 93 54 32 38 61 84 66 27 52 42 79 86
 77 50]
[52 77 77 35 61 33 39 24 18 84 69 89 60 30 66 23 88 97 89 27 79 58 50 31
 52 14 46 11 54 42 57 25  4 93 79 43 46 77 54 86 54 43 57 32 77  3 75 60
 38 50]


In [ ]:
a= np.random.randint(1,10, size = (2,3))
b= np.random.randint(20,30, size = (2,3))


print(a)
print(b)





[[7 3 3]
 [1 4 6]]
[[23 24 23]
 [27 20 23]]


### concatenate

In [16]:
con_row = np.concatenate((a,b), axis=0)
con_col = np.concatenate((a,b), axis=1)

print(con_row)
print(con_col)

[[ 7  3  3]
 [ 1  4  6]
 [23 24 23]
 [27 20 23]]
[[ 7  3  3 23 24 23]
 [ 1  4  6 27 20 23]]


In [20]:
#error

#row wise concetanate korar somoy column same thakbe
#colomn wise concetanate korar somoy row same thakbe
x= np.random.randint(1,10, size = (2,3))
y= np.random.randint(1,10, size = (1,3))


r = np.concatenate((x,y), axis=0) 
r = np.concatenate((x,y), axis=1) 

print(r)



ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

## Transpose Matrix A^T

In [22]:
mat = np.array([
                    [10,20,30],
                    [40,50,60]
                ])

transpose = mat.T

print(transpose)

[[10 40]
 [20 50]
 [30 60]]


### Array Split

In [27]:
import numpy as np

a = np.random.randint(1,10,size=(10,))

splitted_array = np.array_split(a, 3)

print(splitted_array)

# split -> equal division
print(np.split(a,2))


[array([6, 6, 3, 9], dtype=int32), array([8, 2, 1], dtype=int32), array([8, 7, 6], dtype=int32)]
[array([6, 6, 3, 9, 8], dtype=int32), array([2, 1, 8, 7, 6], dtype=int32)]


### Arithmetic Operation and mathematical function

In [32]:
a= np.random.randint(1,10, size = (2,3))
b= np.random.randint(20,30, size = (2,3))

 

print(f"{a+b}\n")
print(f"{np.add(a,b)}\n")

print(f"{a-b}\n")
print(f"{np.subtract(a,b)}\n")

print(f"{a*b}\n")
print(f"{np.multiply(a,b)}\n")

print(f"{a/b}\n")
print(f"{np.divide(a,b)}\n")

print(f"{a//b}\n")
print(f"{np.floor_divide(a,b)}\n")

print(f"{a**b}\n")
print(f"{np.power(a,b)}\n")

print(f"{a%b}\n")
print(f"{np.mod(a,b)}\n")
 


[[32 29 27]
 [30 33 28]]

[[32 29 27]
 [30 33 28]]

[[-22 -27 -21]
 [-20 -15 -24]]

[[-22 -27 -21]
 [-20 -15 -24]]

[[135  28  72]
 [125 216  52]]

[[135  28  72]
 [125 216  52]]

[[0.18518519 0.03571429 0.125     ]
 [0.2        0.375      0.07692308]]

[[0.18518519 0.03571429 0.125     ]
 [0.2        0.375      0.07692308]]

[[0 0 0]
 [0 0 0]]

[[0 0 0]
 [0 0 0]]

[[  -99612771           1 -1038305055]
 [  167814181   -88328767    67108864]]

[[  -99612771           1 -1038305055]
 [  167814181   -88328767    67108864]]

[[5 1 3]
 [5 9 2]]

[[5 1 3]
 [5 9 2]]



# mathemetcal function 


In [68]:
#trigonometry
a= np.random.randint(0,10, size = (1,3))

# sin, cos, tan, degree takes values in radian
sin_val = np.sign(a)
cos_val = np.cos(a)
tan_val = np.tan(a)
deg_con = np.rad2deg(a)

print(f"{a} \n")
print(f"{sin_val}\n")
print(f"{cos_val} \n")
print(f"{tan_val}\n")
print(f"{deg_con}\n")





[[5 0 8]] 

[[1 0 1]]

[[ 0.28366219  1.         -0.14550003]] 

[[-3.38051501  0.         -6.79971146]]

[[286.47889757   0.         458.3662361 ]]



In [85]:
#log
a=[10,9,1]

base_10_val = np.log10(a)
base_2_val = np.log2(a)
sqrt = np.sqrt(a)
print(a)
print(base_10_val)
print(base_2_val)
print(sqrt)
print(np.sum(a))

[10, 9, 1]
[1.         0.95424251 0.        ]
[3.32192809 3.169925   0.        ]
[3.16227766 3.         1.        ]
20


In [90]:
#inplace

x = np.array([10,8,16,100,500,200,2])

z = np.copy(x)
 

print(x)
print(z)
z.sort()
print(z)



print("\n")
sort_arr = np.sort(x)
print(x)
print(sort_arr)

[ 10   8  16 100 500 200   2]
[ 10   8  16 100 500 200   2]
[  2   8  10  16 100 200 500]


[ 10   8  16 100 500 200   2]
[  2   8  10  16 100 200 500]


In [92]:
#2d array sort

mat = np.array([[10,5,3],[8,4,9]])

hor_sort = np.sort(mat, axis=1)
ver_sort = np.sort(mat, axis=0)

print(f"{mat} \n")
print(f"{hor_sort} \n")
print(f"{ver_sort} \n")

[[10  5  3]
 [ 8  4  9]] 

[[ 3  5 10]
 [ 4  8  9]] 

[[ 8  4  3]
 [10  5  9]] 



# Searching

In [105]:
import numpy as np 
x = np.array([10,8,6,25])
print(x)
# np.where(condition, x, y ) if ture then x or if not then replace with y
print(np.where(x==6))
print(np.where(x>6, x, 0))


print(np.where(mat>6, mat, 0))

max_val = np.argmax(x)
min_val = np.argmin(x)
print(max_val)
print(min_val)

[10  8  6 25]
(array([2]),)
[10  8  0 25]
[[10  0  0]
 [ 8  0  9]]
3
2


## counting

In [110]:
a= np.random.randint(0,100, size = (1,100))

print(a)

val_gt_60 = np.count_nonzero(a>60)

print(val_gt_60)


#unique value

print(np.unique(a, return_counts=True))

[[44 67 98 79 96  2 65 54 12 78 78 48 73 16 96 18 29 52 37 94 28 95 99  1
  59  3 29  9 83  4 80 74 54 21 28 12 45 15 97 54 30 74  6 13 11  4 47 49
  21 30 62  5 70 43 59 94  2 28 23 70 26 90 30 73 63 29 62 60 96 31 38 97
  40 11 47 67 85 97 74 66 93 19 98  3  7 83 61 75  9 95 11 85  3 93 49 75
   9 94 10 45]]
42
(array([ 1,  2,  3,  4,  5,  6,  7,  9, 10, 11, 12, 13, 15, 16, 18, 19, 21,
       23, 26, 28, 29, 30, 31, 37, 38, 40, 43, 44, 45, 47, 48, 49, 52, 54,
       59, 60, 61, 62, 63, 65, 66, 67, 70, 73, 74, 75, 78, 79, 80, 83, 85,
       90, 93, 94, 95, 96, 97, 98, 99], dtype=int32), array([1, 2, 3, 2, 1, 1, 1, 3, 1, 3, 2, 1, 1, 1, 1, 1, 2, 1, 1, 3, 3, 3,
       1, 1, 1, 1, 1, 1, 2, 2, 1, 2, 1, 3, 2, 1, 1, 2, 1, 1, 1, 2, 2, 2,
       3, 2, 2, 1, 1, 2, 2, 1, 2, 3, 2, 3, 3, 2, 1]))


## Statistical methods

In [ ]:
#data load 

data = np.genfromtxt("./data/student_scores.csv", delimiter=",", skip_header=1)
print(data)



[[ 1. 85. 80. 90.]
 [ 2. 78. 74. 82.]
 [ 3. 92. 89. 95.]
 [ 4. 88. 90. 87.]
 [ 5. 76. 70. 79.]]


In [122]:
#statistics

math_marks = data[:,:3]

print(math_marks.T)

max_math_marks = np.max(math_marks)
min_math_marks = np.min(math_marks)
print(max_math_marks)
print(min_math_marks)
print(np.mean(math_marks))
print(np.median(math_marks))
print(np.std(math_marks))

[[ 1.  2.  3.  4.  5.]
 [85. 78. 92. 88. 76.]
 [80. 74. 89. 90. 70.]]
92.0
1.0
55.8
76.0
37.806877681183884


In [125]:
#corrcoef  
study_time = np.array([2,3,4,5,6])
marks = np.array([70,75,80,85,90])
correlation = np.corrcoef(study_time, marks)
print(correlation)

[[1. 1.]
 [1. 1.]]


## Linear Algebra

In [ ]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[7,8],[9,10],[11,12]])

C = np.dot(A, B)
print(C)
print(np.trace(B))

[[ 58  64]
 [139 154]]
17


In [131]:
sq_mat = np.array([[1,2,9],[3,4,2],[5,6,8]])
print(np.shape(sq_mat))

det_of_sq_mat = np.linalg.det(sq_mat)
print(det_of_sq_mat)

renk = np.linalg.matrix_rank(sq_mat)
print(renk)

(3, 3)
-25.99999999999998
3
